"""create cognitive_objects table (E3.1 / LIB-01)

Revision ID: 257dc8c23ab1
Revises: 
Create Date: 2026-08-13 00:03:23.826205

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "257dc8c23ab1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cognitive_objects",
        sa.Column("clid", sa.Uuid(), nullable=True),
        sa.Column(
            "accessibility",
            sa.Enum(
                "active",
                "latent",
                "inaccessible",
                "causally_extinct",
                name="accessibility_state",
                native_enum=False,
                length=32,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cognitive_objects")
    # ### end Alembic commands ###
