"""create relationships table (E3.5 / LIB-05)

Revision ID: 2826ce7fa4dc
Revises: 4f8fa05e036c
Create Date: 2026-08-13 17:21:12.368200

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2826ce7fa4dc"
down_revision: str | None = "4f8fa05e036c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "relationships",
        sa.Column("source_coid", sa.Uuid(), nullable=False),
        sa.Column("target_coid", sa.Uuid(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "related_to",
                "references",
                "supports",
                "contradicts",
                "depends_on",
                name="relationship_type",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source_coid != target_coid", name="ck_relationships_no_self_link"),
        sa.ForeignKeyConstraint(
            ["source_coid"],
            ["cognitive_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_coid"],
            ["cognitive_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_coid",
            "target_coid",
            "relationship_type",
            name="uq_relationships_source_target_type",
        ),
    )
    op.create_index(
        op.f("ix_relationships_source_coid"), "relationships", ["source_coid"], unique=False
    )
    op.create_index(
        op.f("ix_relationships_target_coid"), "relationships", ["target_coid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_relationships_target_coid"), table_name="relationships")
    op.drop_index(op.f("ix_relationships_source_coid"), table_name="relationships")
    op.drop_table("relationships")
    # ### end Alembic commands ###
