"""create lineage_edges table (E3.3 / LIB-03)

Revision ID: 4f56e1a4936c
Revises: 257dc8c23ab1
Create Date: 2026-08-13 11:53:16.147248

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f56e1a4936c"
down_revision: str | None = "257dc8c23ab1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lineage_edges",
        sa.Column("parent_coid", sa.Uuid(), nullable=False),
        sa.Column("child_coid", sa.Uuid(), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum(
                "parent",
                "child",
                "branch",
                "merge",
                "derived_from",
                "transformed_from",
                name="lineage_relation",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("parent_coid != child_coid", name="ck_lineage_edges_no_self_link"),
        sa.ForeignKeyConstraint(
            ["child_coid"],
            ["cognitive_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_coid"],
            ["cognitive_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_coid",
            "child_coid",
            "relation_type",
            name="uq_lineage_edges_parent_child_relation",
        ),
    )
    op.create_index(
        op.f("ix_lineage_edges_child_coid"), "lineage_edges", ["child_coid"], unique=False
    )
    op.create_index(
        op.f("ix_lineage_edges_parent_coid"), "lineage_edges", ["parent_coid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lineage_edges_parent_coid"), table_name="lineage_edges")
    op.drop_index(op.f("ix_lineage_edges_child_coid"), table_name="lineage_edges")
    op.drop_table("lineage_edges")
    # ### end Alembic commands ###
