"""add unique current per clid index (E3.4.1)

Revision ID: 4f8fa05e036c
Revises: 2832894b5cb2
Create Date: 2026-08-13 16:22:10.647512

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f8fa05e036c"
down_revision: str | None = "2832894b5cb2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_cognitive_objects_one_current_per_clid",
        "cognitive_objects",
        ["clid"],
        unique=True,
        postgresql_where=sa.text("revision_status = 'current'"),
        sqlite_where=sa.text("revision_status = 'current'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_cognitive_objects_one_current_per_clid",
        table_name="cognitive_objects",
        postgresql_where=sa.text("revision_status = 'current'"),
        sqlite_where=sa.text("revision_status = 'current'"),
    )
    # ### end Alembic commands ###
