"""add trace_id to provenance_records (E3.6.1)

Revision ID: 6bf0c0eb0c2e
Revises: e2c89ee3aa59
Create Date: 2026-08-13 20:02:05.292752

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bf0c0eb0c2e"
down_revision: str | None = "e2c89ee3aa59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("provenance_records", sa.Column("trace_id", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provenance_records", "trace_id")
    # ### end Alembic commands ###
