"""create provenance_records table (E3.6 / LIB-06)

Revision ID: e2c89ee3aa59
Revises: f11551e97026
Create Date: 2026-08-13 19:50:45.448206

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2c89ee3aa59"
down_revision: str | None = "f11551e97026"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provenance_records",
        sa.Column("coid", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "human",
                "agent",
                "import",
                "system",
                name="provenance_source_type",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("source_ref", sa.String(length=512), nullable=True),
        sa.Column(
            "actor_type",
            sa.Enum(
                "human",
                "agent",
                "system",
                name="provenance_actor_type",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("provider_id", sa.String(length=255), nullable=True),
        sa.Column("model_id", sa.String(length=255), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("correlation_id", sa.String(length=255), nullable=True),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("orchestration_run_id", sa.String(length=255), nullable=True),
        sa.Column("agent_role", sa.String(length=64), nullable=True),
        sa.Column("agent_instance_id", sa.String(length=255), nullable=True),
        sa.Column("agent_sequence", sa.Integer(), nullable=True),
        sa.Column("parent_agent_output_ref", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["coid"],
            ["cognitive_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provenance_records_coid"), "provenance_records", ["coid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_provenance_records_coid"), table_name="provenance_records")
    op.drop_table("provenance_records")
    # ### end Alembic commands ###
